databases:
  - name: render_demo
    databaseName: render_demo
    user: render_demo

services:
  - type: web
    name: render_demo
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: render_demo
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false